### ISSUE TITLE
Image push is not working

### ISSUE THREAD

**Issue by chriz2600** [Strider-CD/strider-docker-build#17]
When you use "Push after successful build?" the build fails, because image.push is not invoked correctly in lib/push.js. 
The image.push function from dockerode has the following signature:
Image.prototype.push = function(opts, callback, auth) {...}
In lib/push.js image.push(function() {...}) is used, which leads to an error, when Image.push tries to invoke the callback. I added an empty object as first parameter to image.push, which works for me now.

**Comment by knownasilya** [comment]
Interesting, seems like that API changed (author doesn't follow semver). Think you could submit a PR?

**Comment by chriz2600** [comment]
API (for Image.push) did not change since initial release v0.2.5.

**Comment by knownasilya** [comment]
Weird. It worked before..

**Comment by knownasilya** [comment]
Seems like https://github.com/apocas/dockerode/commit/11d196a5e80f0e5bcec45b82c274db9946b33618 is the culprit.

**Comment by knownasilya** [comment]
@chriz2600 can you give master a try?

**Comment by chriz2600** [comment]
This is exactly the change i made locally. Works! Thank you!

**Comment by knownasilya** [comment]
Ok, I'll release a new version.
